spring:
  application:
    name: MoviesTest
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: ${SPRING_JDBC_URL}
    username: ${SPRING_JDBC_USERNAME}
    password: ${SPRING_JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT}

broker:
  type: ${BROKER_TYPE}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  topic:
    movie-events: ${KAFKA_TOPIC_MOVIE_EVENTS}
    watch-events: ${KAFKA_TOPIC_WATCH_EVENTS}

rabbitmq:
  exchange:
    movie: ${RABBITMQ_EXCHANGE_MOVIE}
  queue:
    movie: ${RABBITMQ_QUEUE_MOVIE}
    watch: ${RABBITMQ_QUEUE_WATCH}
  routing:
    key:
      movie: ${RABBITMQ_ROUTING_KEY_MOVIE}
      watch: ${RABBITMQ_ROUTING_KEY_WATCH}

storage:
  endpoint: ${STORAGE_ENDPOINT}
  accessKey: ${STORAGE_ACCESS_KEY}
  secretKey: ${STORAGE_SECRET_KEY}
  region: ${STORAGE_REGION}
  bucket: ${STORAGE_BUCKET}

jwt:
  secret: ${JWT_SECRET}